language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python test


# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: "Encrypted <access-key-id>="
#   secret_access_key: 
#     secure: "Encypted <secret-access-key>="
#   region: "us-west-2"
#   app: "swe1-app"
#   env: "swe1-app"
#   bucket_name: "elasticbeanstalk-us-west-2-963295565159"