language: python
python:
  - "3.7.8"

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - cd swe1app
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test  # Run tests with coverage
  - coverage report  # Generate coverage report
  
after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "swe-app2"
  env: "swe-app2"
  bucket_name: "elasticbeanstalk-us-west-2-963295565159"
  on:
    all_branches: true
